[package]
name = "pmw3389-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rom_gen"
path = "src/bin/main.rs"

[lib]
name = "pmw3389_driver"
path = "src/lib.rs"

[dependencies]
